export { default as Main } from './Main/Main';
export { default as ChangeInfo } from './ChangeInfo/ChangeInfo';
export { default as Authentication } from './Authentication/Authentication';
export { default as OderHistory } from './OderHistory/OderHistory';
export { default as Cart } from './Cart/Cart';
export { default as Contact } from './Contact/Contact';
export { default as Search } from './Search/Search';
export { default as Shop } from './Shop/Shop';
export { default as PayPage } from './PayPage/PayPage';
